name = "logics_kite"
defaultTargets = ["KiteArith", "KiteModal"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "foundation"
scope = "FormalizedFormalLogic"
version = "git#master"

[[lean_lib]]
name = "LogicsKite"

[[lean_exe]]
name = "KiteArith"
root = "Arith" 
supportInterpreter = true

[[lean_exe]]
name = "KiteModal"
root = "Modal" 
supportInterpreter = true
