name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: typst-community/setup-typst@v4
      - uses: ts-graphviz/setup-graphviz@v2
      - uses: leanprover/lean-action@v1
      - run: |
          lake exec KiteArith
          typst compile ./Arith.typ ./Arith.png
      - run: | 
          lake exec KiteModal
          typst compile ./Modal.typ ./Modal.png
      - name: Create page directory
        run: |
          mkdir _pages
          mv ./Arith.png ./_pages/Arith.png
          mv ./Modal.png ./_pages/Modal.png
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment