name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: ts-graphviz/setup-graphviz@v2
      - name: Generate import graph
        run: | 
          dot -T png ./kite.dot -o kite.png
      - name: Create page directory
        run: |
          mkdir _pages
          mv ./kite.png ./_pages/kite.png
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment